### ISSUE TITLE
Getting really old date

### ISSUE THREAD

**Issue by devrojan** [palicao/phpRedisTimeSeries#21]
Hi,

I'm having problem getting the data it returns a 1970 date. Do you know guys how to fix this problem?
![Capture](https://user-images.githubusercontent.com/50800098/97461427-b944dd00-1978-11eb-83ee-eb7e9238518a.PNG)

**Comment by palicao** [comment]
Hi @devrojan, from what I see the timestamp returned by redis is 2147483, which gets correctly translated to 1970-01-25 ... 
Most likely you were expecting 2147483000 which is today. 
How do you store data in redis? In my understanding timestamps must be provided in milliseconds and not in seconds.
In case this hint doesn't help, can you please provide the full example, including the code which adds the samples?

**Comment by devrojan** [comment]
This is the sample code

```
$ts = new TimeSeries(
    new RedisClient(
        new \Redis(),
        new RedisConnectionParams($host, $port)
    )
);
$ts->add(new Sample('myKey', 32.10));
print_r( $ts->getLastSample('myKey'));
```
In the image below the left side is the result of the code above and on the right side is the result in my redis-cli.
![result](https://user-images.githubusercontent.com/50800098/97536783-a671ed00-19f8-11eb-80b5-b763ccd1fce7.PNG)

**Comment by palicao** [comment]
Thanks, I will investigate that. Could you also tell me which version of redis and php you are using?

**Comment by devrojan** [comment]
PHP Version - 7.2.19
Redis Version - 5.0.7

**Comment by palicao** [comment]
I tried to replicate the behavior with PHP 7.2.34 and Redis 5.0.5 and I couldn't.
Are you sure you are using the latest version of this library?

**Comment by devrojan** [comment]
I'm using this version **"palicao/php-redis-time-series": "^2.1"** . I'm using this library in the Laravel Framework will that be an issue?

**Comment by palicao** [comment]
Ok, sorry I didn't notice it before, but apparently you are running php on a 32 bit system, therefore the timestamp in milliseconds exceeds PHP_INT_MAX!
Please run it on a 64 bit system, otherwise you need to change DateTimeUtils::dateTimeFromTimestampWithMs to work with strings and not with integers.
Maybe I can try to do the change myself anyway but I am ATM pretty busy so it might take a while...

**Comment by palicao** [comment]
@devrojan I tried but failed, the redis extension is already returning overflown integers. Did you manage to test it on a 64-bit machine?
Anyway I will close this issue for now
