### ISSUE TITLE
 Add nightly CI to make sure client don't break

### ISSUE THREAD

**Issue by gkorland** [palicao/phpRedisTimeSeries#9]
Add nightly CI, with Server Edge, to make client doesn't break with server's changes

**Comment by gkorland** [comment]
Use Cron jobs https://docs.travis-ci.com/user/cron-jobs/ with
Docker redislabs/redistimeseries:edge

**Comment by palicao** [comment]
I created an "edge" branch which uses redislabs/redistimeseries:edge and added a travis daily cron. Do you think that's enough or would you recommend something else?

**Comment by gkorland** [comment]
I personally think that having a different branch might make your life harder, forcing you to rebase it each time.
Can't you run the master branch as with edge on the daily cron job only?

**Comment by palicao** [comment]
Yes, I have the same feeling. I would love to have both test running on 1.2.1 and on edge at the same time. I will check if if possible with travis.

**Comment by palicao** [comment]
Ok, done on master! I think I can close this issue now. Thanks @gkorland for the great tip!
